export default {
  GET_ALL_GOODS: 'GET_ALL_GOODS',
  ADD_TO_CART: 'ADD_TO_CART',
  REMOVE_FROM_CART: 'REMOVE_FROM_CART',
  CHANGE_CURRENCY: 'CHANGE_CURRENCY',
  GET_CURRENCY: 'GET_CURRENCY',
  SORT_BY_NAME: 'SORT_BY_NAME',
  SORT_BY_PRICE: 'SORT_BY_PRICE'
}
